# Generated by Django 5.1 on 2025-01-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                (
                    "category_image1",
                    models.ImageField(blank=True, null=True, upload_to="Category"),
                ),
                (
                    "category_image2",
                    models.ImageField(blank=True, null=True, upload_to="Category"),
                ),
                (
                    "category_image3",
                    models.ImageField(blank=True, null=True, upload_to="Category"),
                ),
                (
                    "category_image4",
                    models.ImageField(blank=True, null=True, upload_to="Category"),
                ),
            ],
        ),
    ]
