# Generated by Django 5.1 on 2025-01-12 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_image1",
            new_name="category_image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_image2",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_image3",
        ),
        migrations.RemoveField(
            model_name="category",
            name="category_image4",
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_category_name", models.CharField(max_length=100)),
                (
                    "sub_category_image",
                    models.ImageField(blank=True, null=True, upload_to="SubCategory"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SPANYAPP.category",
                    ),
                ),
            ],
        ),
    ]
