# Generated by Django 5.1 on 2025-01-12 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0002_rename_category_image1_category_category_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=500)),
                (
                    "product_image1",
                    models.ImageField(blank=True, null=True, upload_to="Product"),
                ),
                (
                    "product_image2",
                    models.ImageField(blank=True, null=True, upload_to="Product"),
                ),
                (
                    "product_image3",
                    models.ImageField(blank=True, null=True, upload_to="Product"),
                ),
                (
                    "product_image4",
                    models.ImageField(blank=True, null=True, upload_to="Product"),
                ),
                (
                    "product_image5",
                    models.ImageField(blank=True, null=True, upload_to="Product"),
                ),
                ("Highlights", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("minimum_order_quantity", models.PositiveIntegerField()),
                ("size", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255)),
                ("material", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("specification", models.CharField(max_length=255)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("keyword", models.CharField(blank=True, max_length=1000)),
                ("warenty", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SPANYAPP.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="SPANYAPP.subcategory",
                    ),
                ),
            ],
        ),
    ]
