# Generated by Django 5.1 on 2025-01-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="keyword",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="specification",
            field=models.TextField(),
        ),
    ]
