# Generated by Django 5.1 on 2025-01-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0005_flashsale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashsale",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
