# Generated by Django 5.1 on 2025-01-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0006_alter_flashsale_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="like",
            field=models.BigIntegerField(default=0),
        ),
    ]
