# Generated by Django 5.1 on 2025-01-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0012_shippingaddress_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="city",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="country",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="landmark",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="phone",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="state",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="zipcode",
            field=models.CharField(max_length=20),
        ),
    ]
