# Generated by Django 5.1 on 2025-01-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0015_alter_order_status_alter_orderitems_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="quantity",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
