# Generated by Django 5.1 on 2025-01-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0023_alter_favorites_user_alter_order_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorites",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="user",
        ),
    ]
